import streamlit as st
import google.generativeai as genai
import markdown
import pandas as pd
import io

# 1. SETUP
st.set_page_config(
    page_title="Story Grid Analyzer Pro",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- SECURITY ---
def check_password():
    if "password_correct" not in st.session_state:
        st.session_state.password_correct = False
    if st.session_state.password_correct:
        return True
    st.title("🔒 Login Required")
    password = st.text_input("Enter Password", type="password")
    if st.button("Enter"):
        if password == "story2026": 
            st.session_state.password_correct = True
            st.rerun()
        else:
            st.error("😕 Incorrect password")
    return False

if not check_password():
    st.stop()

# --- SESSION STATE ---
if 'chapter_log' not in st.session_state:
    st.session_state.chapter_log = []
if 'current_report' not in st.session_state:
    st.session_state.current_report = ""

# --- API SETUP ---
try:
    genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])
except:
    st.error("⚠️ API Key missing. Please check Secrets.")

# --- HELPER: DOWNLOAD HTML REPORT ---
def create_html_report(content, title):
    html_content = markdown.markdown(content, extensions=['tables'])
    return f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica', 'Arial', sans-serif; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; text-align: center; padding-bottom: 10px; }}
            h2 {{ color: #e67e22; margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 5px; }}
            h3 {{ color: #2980b9; margin-top: 20px; }}
            ul {{ margin-bottom: 20px; }}
            li {{ margin-bottom: 8px; }}
            strong {{ color: #2c3e50; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; margin-bottom: 20px; font-size: 0.9em; }}
            th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; vertical-align: top; }}
            th {{ background-color: #f8f9fa; color: #2c3e50; font-weight: bold; }}
            tr:nth-child(even) {{ background-color: #f9f9f9; }}
            .footer {{ margin-top: 50px; font-size: 0.8em; color: #999; border-top: 1px solid #eee; padding-top: 10px; text-align: center; }}
        </style>
    </head>
    <body>
        <h1>{title}</h1>
        {html_content}
        <div class="footer">Generated by Story Grid Analyzer Pro</div>
    </body>
    </html>
    """

# --- HELPER: CREATE FORMATTED EXCEL ---
def to_excel(df):
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Story Map')
        workbook = writer.book
        worksheet = writer.sheets['Story Map']
        for i, col in enumerate(df.columns):
            column_len = max(df[col].astype(str).map(len).max(), len(col)) + 2
            if column_len > 100: column_len = 100
            if column_len < 20: column_len = 20
            if "Analysis" in col: column_len = 80     
            worksheet.column_dimensions[chr(65 + i)].width = column_len
        from openpyxl.styles import Alignment
        for row in worksheet.iter_rows():
            for cell in row:
                cell.alignment = Alignment(wrap_text=True, vertical='top')
    processed_data = output.getvalue()
    return processed_data

# --- BRAIN 1: SCENE ANALYZER ---
def analyze_scene(text, genre, framework, beat):
    prompt = f"""
    You are a ruthless Story Grid editor. Analyze this SCENE.
    STYLE: RUTHLESSLY CONCISE. Use Markdown Tables for data. Bullet points for lists.
    CONTEXT: Genre: {genre} | Framework: {framework} | Beat: {beat}
    OUTPUT FORMAT:
    1. HEADER: "# [Emoji] [Start Value] ➔ [End Value]"
    2. THE 5 COMMANDMENTS (Bullet points)
    3. VISUAL SCOREBOARD (Create a Markdown Table with columns: Element, Start Value, End Value, Notes)
    """
    if "None" not in framework:
        prompt += f"\n4. FRAMEWORK CHECK ({framework}): Verdict (✅ PASS / ❌ FAIL) and 1 sentence reason."
    prompt += f"\n5. GENRE CHECK: Gold Star Moment 🌟\n\nSTORY TEXT: {text}"
    model = genai.GenerativeModel('gemini-flash-latest')
    return model.generate_content(prompt).text

# --- BRAIN 2: OUTLINE DOCTOR ---
def analyze_outline(text, genre, framework):
    style_guide = """
    FORMATTING RULES:
    - Use Markdown Headers (##) for sections.
    - Use Bullet Points (*) for lists.
    - Use Markdown Tables for comparisons.
    - Bold key terms.
    """
    if "None" not in framework:
        prompt = f"""
        Analyze this PLOT OUTLINE against {framework} structure.
        {style_guide}
        OUTPUT STRUCTURE: 
        ## 📊 Structural Health Score: [Score]/10
        ## 🩺 Gap Analysis (List beats of {framework})
        ## ⚡ Pacing Check
        """
    else:
        prompt = f"""
        Analyze this PLOT OUTLINE for Global 5 Commandments.
        {style_guide}
        OUTPUT STRUCTURE:
        ## 📊 Narrative Arc Score: [Score]/10
        ## 🌍 Global 5 Commandments Check
        ## 💡 Editor's Notes
        """
    prompt += f"\nOUTLINE TEXT: {text}"
    model = genai.GenerativeModel('gemini-flash-latest')
    return model.generate_content(prompt).text

# --- UI ---
st.title("Story Grid Analyzer Pro 🧬")

# === 📘 GUIDE (REORDERED) ===
with st.expander("📘 How to Use & Why You Need This"):
    st.markdown("""
    ### **Why use this tool?**
    Writing is emotional; editing requires objective distance. This tool acts as your **Ruthless Editor**, checking your work against proven story structures (Story Grid, Save the Cat, etc.) without the sugar-coating.
    
    ### **1. The Outline Doctor (Macro View)**
    * **Goal:** Test your plot structure before you write a single word.
    * **How to use:**
        1. Start in **Tab 1**.
        2. Paste your entire plot summary (1-2 pages).
        3. Click **Diagnose** to see structural holes and pacing issues.
    
    ### **2. The Scene Logger (Micro View)**
    * **Goal:** Ensure every scene turns on a value change.
    * **How to use:**
        1. Switch to **Tab 2** (Scene Logger).
        2. Select your Genre and Framework in the Sidebar.
        3. Paste **one chapter** at a time.
        4. Click **Analyze**.
        5. If the analysis looks accurate, click **➕ Add to Project Table**.
        6. Repeat for all chapters to build your "Book Map."
    
    ### **3. The Book Map (Export)**
    * **Pro Tip:** Scroll to the bottom to download your **Project Excel File**. This gives you a master spreadsheet of every scene's value change, beat type, and analysis.
    """)

with st.sidebar:
    st.header("🎛️ Project Settings")
    st.caption("Logged in")
    selected_genre = st.selectbox("Genre", ["Action/Thriller", "Love Story", "Horror", "Mystery/Crime", "Sci-Fi/Fantasy", "Drama", "Non-Fiction"])
    selected_framework = st.selectbox("Structure Framework", ["None (Pure Story Grid)", "Save the Cat!", "Dan Harmon's Story Circle", "Fichtean Curve"])
    st.divider()
    st.markdown("### 🗑️ Project Data")
    if st.button("Clear Project Table"):
        st.session_state.chapter_log = []
        st.success("Table cleared!")
        st.rerun()

# TABS (SWAPPED ORDER)
tab1, tab2 = st.tabs(["🩺 Outline Doctor", "🔬 Scene Logger"])

# === TAB 1: OUTLINE DOCTOR ===
with tab1:
    st.markdown("### 🚑 Structural Health Check")
    if "None" not in selected_framework:
        st.info(f"Checking against **{selected_framework}** beats.")
    else:
        st.info("Checking for **Global 5 Commandments**.")
    outline_input = st.text_area("Paste Full Plot Outline:", height=300)
    if st.button("Diagnose Outline", type="primary"):
        if outline_input:
            with st.spinner("Diagnosing..."):
                try:
                    diagnosis = analyze_outline(outline_input, selected_genre, selected_framework)
                    st.markdown(diagnosis)
                    html_file = create_html_report(diagnosis, "Outline Health Report")
                    st.download_button("📥 Download Report", html_file, "outline_diagnosis.html", "text/html")
                except Exception as e:
                    st.error(f"Error: {e}")

# === TAB 2: SCENE LOGGER ===
with tab2:
    col1, col2 = st.columns([2, 1])
    with col1:
        st.markdown("### 1. Analyze Chapter")
        chapter_title = st.text_input("Chapter Name", placeholder="e.g. Chapter 1")
        beat_options = ["N/A"]
        if "Save the Cat" in selected_framework:
            beat_options = ["Opening Image", "Catalyst", "Debate", "Fun and Games", "All is Lost", "Finale"]
        elif "Story Circle" in selected_framework:
            beat_options = ["1. YOU", "2. NEED", "3. GO", "4. SEARCH", "5. FIND", "6. TAKE", "7. RETURN", "8. CHANGE"]
        if "None" not in selected_framework:
            selected_beat = st.selectbox("Beat", beat_options)
        else:
            selected_beat = "General Scene"
        scene_input = st.text_area("Paste Text:", height=200, key="scene_in")
        if st.button("🚀 Analyze Scene", type="primary"):
            if scene_input:
                with st.spinner("Analyzing..."):
                    try:
                        report = analyze_scene(scene_input, selected_genre, selected_framework, selected_beat)
                        st.session_state.current_report = report
                        st.rerun()
                    except Exception as e:
                        st.error(f"Error: {e}")
    with col2:
        st.markdown("### 2. Review & Log")
        if st.session_state.current_report:
            st.info("Analysis Ready below ⬇️")
            if st.button("➕ Add to Project Table"):
                new_entry = {
                    "Chapter": chapter_title,
                    "Beat": selected_beat,
                    "Verdict": "See Report", 
                    "Full Analysis": st.session_state.current_report
                }
                st.session_state.chapter_log.append(new_entry)
                st.success(f"Saved {chapter_title}!")
            html_report = create_html_report(st.session_state.current_report, f"Analysis: {chapter_title}")
            st.download_button("📥 Download Report", html_report, f"{chapter_title}_analysis.html", "text/html")
        else:
            st.markdown("*Run analysis to see results.*")
    if st.session_state.current_report:
        st.markdown("---")
        st.markdown(st.session_state.current_report)

# === GLOBAL PROJECT TABLE ===
st.divider()
st.header("📊 Project Table (Book Map)")
if len(st.session_state.chapter_log) > 0:
    df = pd.DataFrame(st.session_state.chapter_log)
    st.dataframe(df, use_container_width=True)
    excel_data = to_excel(df)
    st.download_button(
        label="📥 Download Excel (.xlsx)",
        data=excel_data,
        file_name="story_grid_project.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
else:
    st.info("No chapters logged yet. Analyze a scene in Tab 2 and click 'Add to Project Table'.")