import streamlit as st
import google.generativeai as genai
import markdown  # <--- This is the new translator tool

# --- CONFIGURATION ---
# PASTE YOUR KEY HERE
API_KEY = genai.configure(api_key=st.secrets["GOOGLE_API_KEY"])

if API_KEY == "PASTE_YOUR_NEW_KEY_HERE":
    st.warning("⚠️ Please paste your API Key in the code file (Line 6)")
else:
    genai.configure(api_key=API_KEY)

st.set_page_config(page_title="Story Grid Analyzer", page_icon="📖")

st.title("📖 The Story Grid Analyzer")
st.markdown("Paste your scene below to check the **5 Commandments** and catch continuity errors.")

# Input Area
scene_text = st.text_area("Paste your scene text here:", height=300)

# The "Brain" Logic
if st.button("Analyze Scene"):
    if not scene_text:
        st.warning("Please paste text first.")
    else:
        with st.spinner("Analyzing... (this may take 10-20 seconds)"):
            try:
                # RELIABLE MODEL
                model = genai.GenerativeModel('gemini-flash-latest')
                
                # --- PROMPT: CLEAN LIST FORMAT ---
                prompt = f"""
                Act as a Story Grid editor. Analyze this scene.
                
                1. Identify the 5 Commandments (Inciting Incident, Turning Point, Crisis, Climax, Resolution).
                2. Check for specific continuity errors.
                3. Provide ONE actionable 'Big Fix'.

                OUTPUT FORMAT RULES:
                - Do NOT use Markdown Tables.
                - Use H3 Headers (###) for each Commandment.
                - Use Bullet points for the details.
                - Use Bold labels (e.g. **Explanation:**).
                - Use Emoji bullets (🟢 for pass, 🔴 for fail).
                
                SCENE TEXT:
                {scene_text}
                """
                
                response = model.generate_content(prompt)
                report_text = response.text
                
                # 1. Show Result on Screen (Streamlit likes Markdown)
                st.markdown("### 🤖 The Report Card")
                st.markdown(report_text)
                st.divider()

                # 2. Translate Markdown to HTML for the Download
                # This removes the ### and ** and replaces them with real formatting
                html_body = markdown.markdown(report_text)

                # 3. Create Beautiful HTML Report
                html_report = f"""
                <html>
                <head>
                    <style>
                        /* Professional Document Styling */
                        body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 50px; line-height: 1.6; max-width: 850px; margin: auto; color: #333; }}
                        
                        /* Main Title */
                        h1 {{ color: #2C3E50; border-bottom: 3px solid #2C3E50; padding-bottom: 15px; margin-bottom: 30px; }}
                        
                        /* Commandment Headings (Converted from ###) */
                        h3 {{ 
                            color: #1A5276; 
                            font-size: 1.4em; 
                            margin-top: 35px; 
                            border-bottom: 1px solid #ddd; 
                            padding-bottom: 5px;
                        }}

                        /* Bold Labels (Converted from **) */
                        strong {{ color: #E74C3C; font-weight: 700; }}
                        
                        /* Lists */
                        ul {{ padding-left: 20px; }}
                        li {{ margin-bottom: 8px; }}
                        
                        /* Clean up spacing */
                        p {{ margin-bottom: 15px; }}
                    </style>
                </head>
                <body>
                    <h1>📖 Story Grid Analysis</h1>
                    {html_body}  <hr style="margin-top: 50px; border: 0; border-top: 1px solid #ccc;">
                    <p style="color: #666; font-size: 0.9em;"><em>Generated by your Story Analyzer App</em></p>
                </body>
                </html>
                """

                # OPTION 2: Download as Beautiful Report
                st.download_button(
                    label="📄 Download Beautiful Report (HTML)",
                    data=html_report,
                    file_name="analysis_report.html",
                    mime="text/html"
                )

            except Exception as e:
                st.error(f"Error: {e}")